<a href="https://colab.research.google.com/github/dahlia52/Commercial-District-Analysis/blob/main/code/%EA%B3%A8%EB%AA%A9_%EA%B5%B0%EC%A7%91_%EB%B3%84_VARS_%EC%A7%80%ED%91%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
plt.rc('font', family='NanumBarunGothic')

import seaborn as sns
import numpy as np

In [ ]:
score = pd.read_csv('/content/drive/MyDrive/광진구팟/Data/상권분석/score.csv')
score.head(3)

,상권_코드_명,상권_구분_코드_명,행정동명,상권_변화_지표,임대료_불안정성,전체 매출,업종_종류수,도보 5분 이내 보행자우선도로 개수,가까운 버스정류장까지 거리,650m_반경내_버스_노선수,가까운 지하철역까지 거리,650m_반경내_역수
0,세종대학교,골목상권,군자동,4,2.061089,4.287648e+09,7,3,0.913078,25,0.191643,2
1,장안초등학교,골목상권,군자동,1,2.061089,2.312527e+09,5,5,1.441063,23,0.178571,4
2,능동우편취급국,골목상권,군자동,1,2.061089,1.829857e+10,29,4,0.496948,19,0.137336,0

In [ ]:
nearby = pd.read_csv('/content/drive/MyDrive/광진구팟/Data/골목상권 클러스터.csv')
nearby

       상권_코드_명  label
0     건대입구역 1번      1
1     건대입구역 6번      0
2      광나루역 1번      1
3        광진경찰서      1
4         광진구청      1
5       광진정말공원      0
6      광진정보도서관      0
7       광진초등학교      1
8       구남초등학교      1
9     구의1동주민센터      0
10      구의역 4번      0
11    국립정신건강센터      1
12      군자역 4번      1
13      군자역 5번      1
14     능동우편취급국      0
15      대원고등학교      1
16       동대부여고      1
17      동의초등학교      1
18   뚝섬유원지역 1번      1
19      성동초등학교      1
20      성자초등학교      1
21       세종대학교      1
22      신자초등학교      1
23     아차산역 1번      0
24     아차산역 5번      1
25  어린이대공원역 3번      1
26  어린이대공원역 4번      1
27      용마초등학교      0
28    자양4동주민센터      0
29      자양동우체국      1
30     자양한강도서관      0
31    장로회신학대학교      1
32      장안초등학교      1
33   중곡1동 마을마당      1
34    중곡1동주민센터      1
35    중곡3동주민센터      0
36    중곡4동주민센터      1
37     중곡어린이공원      1
38      중곡역 3번      0
39      푸른동산공원      1
40       해오름공원      1
41       화양사거리      0

In [ ]:
nearby_score = pd.merge(score, nearby, on = '상권_코드_명', how = 'inner')
nearby_score

,상권_코드_명,상권_구분_코드_명,행정동명,상권_변화_지표,임대료_불안정성,전체 매출,업종_종류수,도보 5분 이내 보행자우선도로 개수,가까운 버스정류장까지 거리,650m_반경내_버스_노선수,가까운 지하철역까지 거리,650m_반경내_역수,label
0,세종대학교,골목상권,군자동,4,2.061089,4.287648e+09,7,3,0.913078,25,0.191643,2,1
1,장안초등학교,골목상권,군자동,1,2.061089,2.312527e+09,5,5,1.441063,23,0.178571,4,1
2,능동우편취급국,골목상권,군자동,1,2.061089,1.829857e+10,29,4,0.496948,19,0.137336,0,0
3,중곡1동 마을마당,골목상권,중곡1동,2,2.198997,1.150311e+10,14,0,0.319969,19,0.113677,0,1
4,중곡1동주민센터,골목상권,중곡1동,1,2.198997,1.088088e+09,6,0,0.900737,25,0.141239,0,1
5,중곡어린이공원,골목상권,중곡1동,4,2.198997,6.151680e+09,13,0,0.446603,11,0.129757,0,1
6,광진경찰서,골목상권,구의1동,4,2.964346,2.539555e+09,9,1,0.351619,21,0.167972,4,1
7,구의1동주민센터,골목상권,구의1동,1,2.964346,3.362525e+10,31,4,0.666905,13,0.124603,0,0
8,동대부여고,골목상권,구의1동,1,2.964346,1.291220e+10,25,4,0.578771,13,0.119904,0,1
9,신자초등학교,골목상권,자양3동,3,3.045725,1.407709e+10,28,0,1.684848,22,0.216265,4,1
10,뚝섬유원지역 1번,골목상권,자양3동,3,3.045725,5.258867e+09,15,1,1.203250,27,0.195208,11,1
11,자양한강도서관,골목상권,자양2동,1,2.019069,2.800362e+10,31,0,2.368266,15,0.127619,0,0
12,성동초등학교,골목상권,자양2동,4,2.019069,1.502494e+10,23,0,0.566054,20,0.453647,5,1
13,자양동우체국,골목상권,자양2동,1,2.019069,1.031613e+10,29,1,1.051072,17,0.133804,0,1
14,성자초등학교,골목상권,자양2동,2,2.019069,1.953902e+10,33,1,0.459150,18,0.221331,5,1
15,광진정말공원,골목상권,자양1동,1,5.360563,2.469154e+10,32,2,1.239331,11,0.139942,0,0
16,광진구청,골목상권,자양1동,3,5.360563,8.663238e+09,15,5,0.268628,28,0.183098,6,1
17,구의역 4번,골목상권,자양1동,1,5.360563,4.461443e+10,43,5,3.295187,19,0.178932,5,0
18,어린이대공원역 4번,골목상권,화양동,1,2.713627,3.988366e+09,8,5,0.914358,24,0.217356,4,1
19,어린이대공원역 3번,골목상권,화양동,3,2.713627,7.651018e+09,11,5,0.578395,23,1.252885,4,1
20,건대입구역 1번,골목상권,화양동,1,2.713627,1.166689e+10,17,2,0.586413,20,0.133291,0,1
21,화양사거리,골목상권,화양동,1,2.713627,2.838047e+10,24,5,0.450137,11,0.130169,0,0
22,광진정보도서관,골목상권,광장동,1,2.452189,3.247321e+10,21,0,0.382182,3,0.124082,0,0
23,광나루역 1번,골목상권,광장동,3,2.452189,1.770376e+10,14,0,0.379337,6,0.220105,5,1
24,장로회신학대학교,골목상권,광장동,3,2.452189,3.639348e+09,10,0,0.188666,2,0.139853,0,1
25,자양4동주민센터,골목상권,자양4동,2,2.083333,2.788708e+10,34,1,0.636164,25,0.141877,0,0
26,건대입구역 6번,골목상권,자양4동,1,2.083333,6.656748e+10,37,1,0.908937,28,0.204026,8,0
27,아차산역 5번,골목상권,능동,1,2.613542,2.455047e+10,5,1,1.725217,24,0.303703,2,1
28,군자역 5번,골목상권,능동,1,2.613542,1.395446e+10,15,2,1.274501,25,0.770105,2,1
29,동의초등학교,골목상권,구의2동,1,3.230853,1.326059e+09,10,1,2.521777,12,0.206028,6,1
30,광진초등학교,골목상권,구의2동,3,3.230853,9.738513e+09,16,0,0.481184,17,0.334589,6,1
31,대원고등학교,골목상권,중곡4동,1,2.193700,7.253295e+09,20,0,2.337433,19,0.555064,3,1
32,아차산역 1번,골목상권,중곡4동,1,2.193700,3.019082e+10,34,1,2.190957,13,0.148313,0,0
33,해오름공원,골목상권,중곡4동,1,2.193700,1.138369e+10,28,0,0.608075,10,0.136052,0,1
34,중곡4동주민센터,골목상권,중곡4동,2,2.193700,3.543721e+09,7,0,1.520748,12,0.225987,3,1
35,구남초등학교,골목상권,구의3동,1,5.513178,8.864691e+09,13,2,2.405923,19,0.274985,7,1
36,푸른동산공원,골목상권,구의3동,1,5.513178,6.979311e+09,17,0,1.630682,13,0.113912,0,1
37,국립정신건강센터,골목상권,중곡2동,1,2.407019,1.588389e+10,25,0,0.935894,19,0.671520,3,1
38,군자역 4번,골목상권,중곡2동,1,2.407019,8.615755e+09,18,2,0.770903,27,0.219374,5,1
39,용마초등학교,골목상권,중곡2동,4,2.407019,3.072600e+10,37,0,1.123989,19,0.184184,5,0
40,중곡역 3번,골목상권,중곡3동,1,3.651484,2.219462e+10,32,0,0.672743,18,0.161988,3,0
41,중곡3동주민센터,골목상권,중곡3동,1,3.651484,3.097699e+10,36,0,0.556913,11,0.130741,0,0

In [ ]:
nearby_score0 = nearby_score[nearby_score.label == 0]
nearby_score0

,상권_코드_명,상권_구분_코드_명,행정동명,상권_변화_지표,임대료_불안정성,전체 매출,업종_종류수,도보 5분 이내 보행자우선도로 개수,가까운 버스정류장까지 거리,650m_반경내_버스_노선수,가까운 지하철역까지 거리,650m_반경내_역수,label
2,능동우편취급국,골목상권,군자동,1,2.061089,1.829857e+10,29,4,0.496948,19,0.137336,0,0
7,구의1동주민센터,골목상권,구의1동,1,2.964346,3.362525e+10,31,4,0.666905,13,0.124603,0,0
11,자양한강도서관,골목상권,자양2동,1,2.019069,2.800362e+10,31,0,2.368266,15,0.127619,0,0
15,광진정말공원,골목상권,자양1동,1,5.360563,2.469154e+10,32,2,1.239331,11,0.139942,0,0
17,구의역 4번,골목상권,자양1동,1,5.360563,4.461443e+10,43,5,3.295187,19,0.178932,5,0
21,화양사거리,골목상권,화양동,1,2.713627,2.838047e+10,24,5,0.450137,11,0.130169,0,0
22,광진정보도서관,골목상권,광장동,1,2.452189,3.247321e+10,21,0,0.382182,3,0.124082,0,0
25,자양4동주민센터,골목상권,자양4동,2,2.083333,2.788708e+10,34,1,0.636164,25,0.141877,0,0
26,건대입구역 6번,골목상권,자양4동,1,2.083333,6.656748e+10,37,1,0.908937,28,0.204026,8,0
32,아차산역 1번,골목상권,중곡4동,1,2.193700,3.019082e+10,34,1,2.190957,13,0.148313,0,0
39,용마초등학교,골목상권,중곡2동,4,2.407019,3.072600e+10,37,0,1.123989,19,0.184184,5,0
40,중곡역 3번,골목상권,중곡3동,1,3.651484,2.219462e+10,32,0,0.672743,18,0.161988,3,0
41,중곡3동주민센터,골목상권,중곡3동,1,3.651484,3.097699e+10,36,0,0.556913,11,0.130741,0,0

In [ ]:
nearby_score0['도보 5분 이내 보행자우선도로 개수'].mean()

1.7692307692307692

In [ ]:
nearby_score0['가까운 버스정류장까지 거리'].mean()

1.1529737467358565

In [ ]:
nearby_score0['650m_반경내_버스_노선수'].mean()

15.76923076923077

In [ ]:
nearby_score0['가까운 지하철역까지 거리'].mean()

0.14875473102361683

In [ ]:
nearby_score1 = nearby_score[nearby_score.label == 1]
nearby_score1

,상권_코드_명,상권_구분_코드_명,행정동명,상권_변화_지표,임대료_불안정성,전체 매출,업종_종류수,도보 5분 이내 보행자우선도로 개수,가까운 버스정류장까지 거리,650m_반경내_버스_노선수,가까운 지하철역까지 거리,650m_반경내_역수,label
0,세종대학교,골목상권,군자동,4,2.061089,4.287648e+09,7,3,0.913078,25,0.191643,2,1
1,장안초등학교,골목상권,군자동,1,2.061089,2.312527e+09,5,5,1.441063,23,0.178571,4,1
3,중곡1동 마을마당,골목상권,중곡1동,2,2.198997,1.150311e+10,14,0,0.319969,19,0.113677,0,1
4,중곡1동주민센터,골목상권,중곡1동,1,2.198997,1.088088e+09,6,0,0.900737,25,0.141239,0,1
5,중곡어린이공원,골목상권,중곡1동,4,2.198997,6.151680e+09,13,0,0.446603,11,0.129757,0,1
6,광진경찰서,골목상권,구의1동,4,2.964346,2.539555e+09,9,1,0.351619,21,0.167972,4,1
8,동대부여고,골목상권,구의1동,1,2.964346,1.291220e+10,25,4,0.578771,13,0.119904,0,1
9,신자초등학교,골목상권,자양3동,3,3.045725,1.407709e+10,28,0,1.684848,22,0.216265,4,1
10,뚝섬유원지역 1번,골목상권,자양3동,3,3.045725,5.258867e+09,15,1,1.203250,27,0.195208,11,1
12,성동초등학교,골목상권,자양2동,4,2.019069,1.502494e+10,23,0,0.566054,20,0.453647,5,1
13,자양동우체국,골목상권,자양2동,1,2.019069,1.031613e+10,29,1,1.051072,17,0.133804,0,1
14,성자초등학교,골목상권,자양2동,2,2.019069,1.953902e+10,33,1,0.459150,18,0.221331,5,1
16,광진구청,골목상권,자양1동,3,5.360563,8.663238e+09,15,5,0.268628,28,0.183098,6,1
18,어린이대공원역 4번,골목상권,화양동,1,2.713627,3.988366e+09,8,5,0.914358,24,0.217356,4,1
19,어린이대공원역 3번,골목상권,화양동,3,2.713627,7.651018e+09,11,5,0.578395,23,1.252885,4,1
20,건대입구역 1번,골목상권,화양동,1,2.713627,1.166689e+10,17,2,0.586413,20,0.133291,0,1
23,광나루역 1번,골목상권,광장동,3,2.452189,1.770376e+10,14,0,0.379337,6,0.220105,5,1
24,장로회신학대학교,골목상권,광장동,3,2.452189,3.639348e+09,10,0,0.188666,2,0.139853,0,1
27,아차산역 5번,골목상권,능동,1,2.613542,2.455047e+10,5,1,1.725217,24,0.303703,2,1
28,군자역 5번,골목상권,능동,1,2.613542,1.395446e+10,15,2,1.274501,25,0.770105,2,1
29,동의초등학교,골목상권,구의2동,1,3.230853,1.326059e+09,10,1,2.521777,12,0.206028,6,1
30,광진초등학교,골목상권,구의2동,3,3.230853,9.738513e+09,16,0,0.481184,17,0.334589,6,1
31,대원고등학교,골목상권,중곡4동,1,2.193700,7.253295e+09,20,0,2.337433,19,0.555064,3,1
33,해오름공원,골목상권,중곡4동,1,2.193700,1.138369e+10,28,0,0.608075,10,0.136052,0,1
34,중곡4동주민센터,골목상권,중곡4동,2,2.193700,3.543721e+09,7,0,1.520748,12,0.225987,3,1
35,구남초등학교,골목상권,구의3동,1,5.513178,8.864691e+09,13,2,2.405923,19,0.274985,7,1
36,푸른동산공원,골목상권,구의3동,1,5.513178,6.979311e+09,17,0,1.630682,13,0.113912,0,1
37,국립정신건강센터,골목상권,중곡2동,1,2.407019,1.588389e+10,25,0,0.935894,19,0.671520,3,1
38,군자역 4번,골목상권,중곡2동,1,2.407019,8.615755e+09,18,2,0.770903,27,0.219374,5,1

In [ ]:
nearby_score1['도보 5분 이내 보행자우선도로 개수'].mean()

1.4137931034482758

In [ ]:
nearby_score1['가까운 버스정류장까지 거리'].mean()

1.0015292090532617

In [ ]:
nearby_score1['650m_반경내_버스_노선수'].mean()

18.655172413793103

In [ ]:
nearby_score1['가까운 지하철역까지 거리'].mean()

0.28348011470709644